/** @type {import('@docusaurus/types').DocusaurusConfig} */
module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  docs: ["intro"],
  examples: [
    {
      type: "ref",
      id: "examples",
    },
  ],
};
